/*
 * ファイル名 : CommonBaseDao.java
 * 作成者     : 日立ソフト
 * 作成日     : 2012/5/24
 * 変更履歴   :
 *    日付       更新者        内容
 *  2012/5/24  日立ソフト    初版作成
 */
package jp.hitachisoft.jfk.batch.common.db.dao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

import jp.hitachisoft.jfk.batch.common.BatchCommonConst;
import jp.hitachisoft.jfk.batch.common.bean.BatchInputInfo;
import jp.hitachisoft.jfk.batch.common.dbaccess.BatchBaseDAO;
import jp.hitachisoft.jfk.batch.common.exception.BatchSystemException;
import jp.hitachisoft.jfk.batch.common.log.BatchLogInfo;
import jp.hitachisoft.jfk.batch.common.util.CommonConst;
import jp.hitachisoft.jfk.commons.common.LogMessageId;


/**
 * クラス名：CommonBaseDao
 * 機能概要：DBサーバ日時取得DAO
 * @author 日立ソフト
 * @version 2.0
 */
public class CommonBaseDao extends BatchBaseDAO {
	private static Connection conn = null;

	/**
     * This method was generated by Abator4JFK for JFK.
     * This method corresponds to the database table BC_MST_MENU_CLSF
     * @param inputInfo
     * @param connection
     * @abatorgenerated Mon Sep 22 15:46:54 JST 2008
     */
    public CommonBaseDao(BatchInputInfo inputInfo, Connection connection) {
        super(inputInfo,connection);
        conn = connection;
    }

    /**
     * This method was generated by Abator4JFK for JFK.
     * This method corresponds to the database table BC_MST_MENU_CLSF
     * @param inputInfo
     * @return currentTimestamp
     * @throws BatchSystemException
     * @abatorgenerated Mon Sep 22 15:46:54 JST 2008
     */
    public Date selectTimestamp() throws BatchSystemException {
		ResultSet rs = null;
		//検索実行し、結果を取得
		Date currentTimestamp = null;
		try {
			// 使用SQLID初期化
			String sqlId = null;
			// リソース名取得
			String resource = conn.getMetaData().getDatabaseProductName();
			// リソース名判定
			if (resource.equals(CommonConst.RDBMS_ORACLE)){
				// リソース名が"Oracle"の場合
				// Oracle用のSQLIDを設定
				sqlId = CommonConst.SELECT_TIMESTAMP_ORACLE;
			} else if (resource.equals(CommonConst.RDBMS_POSTGRESQL)){
				// リソース名が"PostgreSQL"の場合
				// PostgreSQLのSQLIDを設定
				sqlId = CommonConst.SELECT_TIMESTAMP_POSTGRESQL;
			}
			if (getPstmt() == null) {
				loadPreparedStatement(BatchCommonConst.SQLMAP_FILE, sqlId, null);
			}
			rs = getPstmt().executeQuery();
			if (rs.next()) {
				currentTimestamp = rs.getTimestamp("CURRENT_TIMESTAMP");
			}
		} catch (SQLException e) {

			BatchLogInfo logInfo = new BatchLogInfo(LogMessageId.MECO00006, e.getMessage(), e);  //ログ出力
            throw new BatchSystemException(logInfo);
		} finally {
			try {
				if (rs != null) {
					rs.close();
					rs = null;
				}
			} catch (SQLException e) {
                BatchLogInfo logInfo = new BatchLogInfo(LogMessageId.MECO00046, e.getMessage(), e);  //ログ出力
                throw new BatchSystemException(logInfo);
			}
		}
        return currentTimestamp;
    }
}